'use client'


import { Separator } from "@/components/ui/separator";
import { totalCategories, totalPosts, totalUsers } from "@/utils/actions/count/counts";
import { useEffect, useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { BarChartBetter } from "@/components/bar-chart";
import { BarChartComponent } from "@/components/bar-chart-simple";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { useUser } from "@clerk/nextjs";
import { ContentTemplate } from "@/type";
import { getByClerkId } from "@/utils/actions/user/user";
import { GetPostById } from "@/utils/actions/blog/getbyId";
import Image from "next/image";

interface Post {
  id: string;
  title: string;
  content: string;
  image?: string | null;
  created_at: Date;
}

export default function Dashboard() {
  const [stats, setStats] = useState<any>({ posts: 200, categories: 100, users: 50000 });
  const { user } = useUser();
  const [posts, setPosts] = useState<Post[]>([]);

  useEffect(() => {
    const fetchPosts = async () => {
      if (user) {
        const fetchedUser = await getByClerkId(user.id);
        const userId = fetchedUser?.id ?? null;
        if (userId) {
          const fetchedPosts = await GetPostById(userId);
          setPosts(fetchedPosts);
        }
      }
    };
    fetchPosts();
  }, [user]);

   


  return (
    <div className="flex flex-col gap-6 p-6 bg-gray-100">
      <h1 className="text-4xl font-bold mb-6 text-gray-800">Dashboard</h1>
      
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {[
          { title: "Total Posts", value: stats.posts },
          { title: "Total Categories", value: stats.categories },
          { title: "Total Users", value: stats.users },
        ].map((stat, index) => (
          <Card key={index}>
            <CardHeader>
              <CardTitle>{stat.title}</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-3xl font-bold text-blue-600">{stat.value}</p>
            </CardContent>
          </Card>
        ))}
      </div>

      <div className="flex flex-wrap gap-6 mt-6">
      <BarChartComponent />
        <BarChartBetter />
      </div>
    

      <div className="grid md:grid-cols-2 gap-6 mt-6">
        <Card>
          <CardHeader className="flex justify-between items-center">
            <div>
              <CardTitle>Latest Projects</CardTitle>
              <CardDescription>Recent projects generated by the system</CardDescription>
            </div>
            <Button asChild size="sm" variant="outline">
              {posts ? 
              <Link href="/dashboard/posts">
                View All
                <ArrowUpRight className="h-4 w-4 ml-1" />
              </Link>
              :
              <Link href="/dashboard/addPost">
              Create New Project
              <ArrowUpRight className="h-4 w-4 ml-1" />
            </Link>
          }
            </Button>
          </CardHeader>
          <CardContent className="overflow-y-auto max-h-96">
            <div className="grid gap-4">
              {posts.length > 0 ? (
                posts.map((post) => (
                  <article key={post.id} className="rounded-lg shadow hover:shadow-lg transition">
                    <Image
                      alt="Project Thumbnail"
                      height={200}
                      width={300}
                      src={post.image ?? 'https://via.placeholder.com/400'}
                      className="w-full h-40 object-cover rounded-t-lg"
                    />
                    <div className="p-4">
                      <time dateTime={post.created_at.toISOString()} className="block text-xs text-gray-500 mb-1">
                        {new Date(post.created_at).toLocaleDateString()}
                      </time>
                      <Link href={`/dashboard/posts/${post.id}`}>
                        <h3 className="text-lg font-semibold dark:text-white text-gray-600 ">{post.title}</h3>
                      </Link>
                      <p className="mt-2 dark:text-white text-gray-600 line-clamp-2">
                        {post.content}
                      </p>
                    </div>
                  </article>
                ))
              ) : (
                <p className="text-center text-gray-500">No projects to display</p>
              )}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
